# Generated by Django 5.1.3 on 2024-12-03 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_offer_category_delete_categorymodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='offer',
            name='category',
            field=models.ManyToManyField(related_name='offers', to='app.categorymodel'),
        ),
    ]
