# Generated by Django 5.1.3 on 2024-12-03 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_categorymodel_offer_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='category',
            field=models.ManyToManyField(blank=True, null=True, related_name='offers', to='app.categorymodel'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='product',
            field=models.ManyToManyField(blank=True, null=True, related_name='offers', to='app.product'),
        ),
    ]
