# Generated by Django 5.1.3 on 2024-12-07 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_offer_category_alter_offer_product'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='offer',
            options={'permissions': [('can_view_offer', 'The user can view the offer')]},
        ),
        migrations.AlterField(
            model_name='offer',
            name='category',
            field=models.ManyToManyField(blank=True, related_name='offers', to='app.categorymodel'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='product',
            field=models.ManyToManyField(blank=True, related_name='offers', to='app.product'),
        ),
    ]
