# Generated by Django 5.1.1 on 2024-12-10 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_discountcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='discountcode',
            name='lucky_user',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
