# Generated by Django 5.1.1 on 2024-12-12 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_productsizestock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='sizes',
        ),
    ]
